name: BlaBla
#глобальные хуйни
env:
  APPLICATION_NAME: "My proj"
  DEPLOY_PACKAGE_NAME: "proj-deploy-ver${{github.sha}}" #токен коммита
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  my-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World Message
        run: echo "hello world"
      - name: Exexute few commands
        run: |
              echo "hello1"
              echo "hello2"
              echo "Application name ${{env.DEPLOY_PACKAGE_NAME}}"
      - name: List current folder
        run: ls -la
      - name: git clone my repo
        uses: actions/checkout@v1
      - name: List current folder
        run: ls -la
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-testing] # данный джоб начнется после выполнения my-testing
    steps:
      - name: Print Hello World Message
        run: echo "hello world"
      - name: Printing packages
        run: |
              echo "Package name ${{env.APPLICATION_NAME}}"
