name: BlaBla
#глобальные хуйни
env:
  APPLICATION_NAME: "My proj"
  DEPLOY_PACKAGE_NAME: "proj-deploy-ver${{github.sha}}" #токе коммита
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  my-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World Message
        run: echo "hello world"
      - name: Exexute few commands
        run: |
              echo "hello1"
              echo "hello2"
              echo "Application name {{env.DEPLOY_PACKAGE_NAME}}"
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-testing] # данный джоб начнется после выполнения my-testing
    steps:
      - name: Print Hello World Message
        run: echo "hello world"
      - name: Printing packages
        run: |
              echo "Package name {{env.APPLICATION_NAME}}"
